---
# Dependency management (download roles/collections)
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "rmenage/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    #  - dependency
    - create
    #  - prepare
    - converge
    - idempotence
    - verify
    #  - cleanup
    - destroy
